### PR TITLE
Fix gitBranch() to work without sh

### PR DESCRIPTION
**Pull request by zsoltk**
@vanniktech check this out.

### CODE REVIEW

**Comment by vanniktech** [comment]
Oh jesus that's super fancy. What is this crazy syntax (`=~ /(?m)\* (.*)$/)[0][1]`), Groovy?

**Comment by zsoltk** [comment]
Yep.

=~ regex match
(?m) multiline matching
the rest of the regex pattern is self-explanatory
[0][1] array access of matches

TIL :)

**Comment by vanniktech** [comment]
TIL indeed. Nice one @zsoltk when can we expect a new release?

**Comment by zsoltk** [comment]
I just pushed 1.2.7 to sonatype. It should be available in a couple of hours.

**Comment by vanniktech** [comment]
Okay nice what happened with 1.2.5 and 1.2.6? I can't find any information on those releases.

**Comment by zsoltk** [comment]
I released those as well, just my hands were faster than my thoughts. 1.2.5 is your first solution which produces an empty value, 1.2.6 is the one with the subshell.

**Pull request merged**
