### PR TITLE
Fix gitBranch()

### PR DESCRIPTION
**Pull request by vanniktech**
Found a way which only does use git.

Plus I changed the tests so they fail if the string is empty.

Overall: gitBranch works now :)

### CODE REVIEW

**Comment by vanniktech** [comment]
@zsoltk all integration tests are now throwing this exception:

> java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:

Didn't you say somewhere once that you also faced that issue and somehow got around it?

**Comment by zsoltk** [comment]
I thought I got around it, but didn't. From time to time it fails with the above, and I'd be more than glad to solve it. As of yet, I don't know what else to try. Until then, just push again.

**Comment by vanniktech** [comment]
Hmm now every test runs. Though the `gitBranch` test method fails. I tested it locally against my phone and there it did work properly. Do you have any ideas?

**Comment by zsoltk** [comment]
Yes. Travis checks out the PR as a reference:

```
git fetch origin +refs/pull/41/merge
git checkout -qf FETCH_HEAD
```

So it ends up in detached HEAD state. There will be no current branch.

**Comment by zsoltk** [comment]
So when running `git symbolic-ref --short HEAD` in the shell, it will return:
`fatal: ref HEAD is not a symbolic ref`

**Comment by zsoltk** [comment]
Your original solution using `git branch | sed -n "/\\* /s///p"` would work without an error and return `(HEAD detached at FETCH_HEAD)` in this case, so if you could determine why it will return an empty string instead when called from inside gradle, everything would be fine I guess.

**Comment by zsoltk** [comment]
It surely relates to piping the output. Calling `shell("git branch")` works, but `shell("git branch | head -n 1")` will output an empty string.

**Comment by vanniktech** [comment]
Yup I also had the feeling that the piping does not work. Though I don't know how to fix that.

Isn't this behavior `fatal: ref HEAD is not a symbolic ref` 'good enough' since you are essentially not on a branch and hence returning an empty string is okay?

**Comment by zsoltk** [comment]
I'd refrain from that since you can't distinguish between an intended empty string and an erroneous result this way.

Google `gradle exec pipe`?

Or maybe instead of `sed`, handle the output of `git branch` inside gradle?

**Comment by zsoltk** [comment]
Or maybe https://github.com/ajoberstar/grgit

**Comment by vanniktech** [comment]
@zsoltk I'm now getting lint complains, should we update the libraries?

**Comment by zsoltk** [comment]
What kind of lint complaints?

**Comment by vanniktech** [comment]
> /home/travis/build/zsoltk/paperwork/paperwork-integration/build.gradle:79: Error: A newer version of com.android.support:appcompat-v7 than 23.1.1 is available: 23.2.0 [GradleDependency]
>     compile 'com.android.support:appcompat-v7:23.1.1'
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/travis/build/zsoltk/paperwork/paperwork-integration/build.gradle:83: Error: A newer version of com.android.support:support-annotations than 23.1.1 is available: 23.2.0 [GradleDependency]
>     androidTestCompile "com.android.support:support-annotations:23.1.1"
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    Explanation for issues of type "GradleDependency":
>    This detector looks for usages of libraries where the version you are using
>    is not the current stable release. Using older versions is fine, and there
>    are cases where you deliberately want to stick with an older version.
>    However, you may simply not be aware that a more recent version is
>    available, and that is what this lint check helps find.
> 2 errors, 0 warnings
> Wrote HTML report to file:///home/travis/build/zsoltk/paperwork/paperwork-integration/build/outputs/lint-results.html
> Wrote XML report to file:///home/travis/build/zsoltk/paperwork/paperwork-integration/build/outputs/lint-results.xml
> :paperwork-integration:lint FAILED
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':paperwork-integration:lint'.
>   Lint found errors in the project; aborting build.
>   Fix the issues identified by lint, or add the following to your build script to proceed with errors:
>   ...
>   android {
>       lintOptions {
>           abortOnError false
>       }
>   }
>   ...
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>   BUILD FAILED
>   Total time: 1 mins 31.648 secs

**Comment by zsoltk** [comment]
Ah. Ok. Merged #42, thanks.

**Comment by vanniktech** [comment]
@zsoltk seems to be working fine now

**Comment by zsoltk** [comment]
@vanniktech Nice work, thank you!

**Comment by zsoltk** [comment]
I'm trying not to give you a headache, but how about environments without `sh` though?

**Comment by vanniktech** [comment]
Hmm I think they just lost ? :D

**Comment by zsoltk** [comment]
Yeah they didn't roll 6 in this round, too bad. No, that's not how I would approach it :)

**Comment by zsoltk** [comment]
See #43

**Pull request merged**
