### PR TITLE
Remove unnecessary tests

### PR DESCRIPTION
**Pull request by vanniktech**
They're not really adding any value.

Do you plan to write some tests for the core functionality though (Java API and Gradle Plugin)?

### CODE REVIEW

**Comment by zsoltk** [comment]
Thanks, I left the auto-generated test classes there exactly to remind me that real tests should be written. 

Absolutely. I'm really not sure though how to approach testing the gradle plugin. Any ideas?

**Comment by vanniktech** [comment]
Yup I have some ideas. I'll reference it in #8 & #9.

**Comment by zsoltk** [comment]
@vanniktech any further input please?

**Comment by vanniktech** [comment]
Not yet. I'd say we first work on 1.2 and then add some tests since 1.2 breaks more or less the api. 

Also I'd then refer to the two issues you created. We shouldn't use this PR anymore. 

On 3 January 2016 22:45:45 CET, Zsolt Kocsi notifications@github.com wrote:

> @vanniktech any further input please?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zsoltk/paperwork/pull/7#issuecomment-168542996

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zsoltk** [comment]
Agreed.

**Pull request merged**
