### PR TITLE
Add helper method gitBranch

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by zsoltk** [comment]
Nice, thanks!

I wonder why the PR didn't trigger a build in travis. Any ideas?

**Comment by vanniktech** [comment]
@zsoltk puh no idea ...

**Comment by zsoltk** [comment]
Please amend / rebase the commit unchanged and push again, in hopes that it will trigger it this time. If it doesn't, please execute `scripts/run-tests.sh` and tell me it's all green.

**Comment by vanniktech** [comment]
@zsoltk done. Plus it seems like Travis is now running

**Comment by zsoltk** [comment]
Thanks! I'll release 1.2.5 to include this PR soon.

**Comment by vanniktech** [comment]
@zsoltk nice and thanks!

**Comment by zsoltk** [comment]
Problem is, gitBranch() returns an empty string. The command to run is ok, when I paste it in a console it returns what it should, but somehow inside gradle it won't. It even displays as an empty string in the integration test (which sheds light to another problem: the integration test matchers will let an empty string pass through).

Could you look into it please?

**Comment by vanniktech** [comment]
Yup. I'm getting an error though when I try to open the project in Android Studio. (The changes for this PR, I did with sublime).

> Error:(1, 0) Cause: startup failed:
> build file '/Users/nik/tmp/paperwork/paperwork-integration/build.gradle': 1: unable to resolve class hu.supercluster.paperwork.plugin.PaperworkPlugin
>  @ line 1, column 1.
>    import hu.supercluster.paperwork.plugin.PaperworkPlugin
>    ^

**Comment by zsoltk** [comment]
Yep. I've observed this with the new Android Studio 2.0 beta as well. Run `./gradlew` in the console manually, it will solve it. (AS runs gradle on its own and skips that script - and remember, there's the PaperworkPlugin copy-over functionality embedded in that)

**Comment by vanniktech** [comment]
Hmm okay I found the error. 

`cp paperwork-plugin/src/main/groovy/* buildSrc/src/main/groovy/ -r` is not a valid syntax.

Output

> usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
>        cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

`-r` has to be in the beginning:

`cp -r paperwork-plugin/src/main/groovy/* buildSrc/src/main/groovy/`

Created #40 for that.

**Comment by zsoltk** [comment]
Merged #40.

**Comment by vanniktech** [comment]
@zsoltk I found a way to make gitBranch work and also improved a few tests a bit -> #41

**Pull request merged**
